pipeline:
    name: cid
    identifier: cid
    allowStageExecutions: false
    projectIdentifier: collci
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: quicks
                build: <+input>
    stages:
        - stage:
              name: Build Test and Push
              identifier: Build_Test_and_Push
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: cidelegate
                          namespace: harness-delegate-ng
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: Run Unit Tests
                                identifier: Run_Unit_Tests
                                spec:
                                    connectorRef: account.harnessImage
                                    image: node:10
                                    command: npm test
                          - step:
                                type: BuildAndPushDockerRegistry
                                name: Build and push image to Docker Hub
                                identifier: Build_and_push_image_to_Docker_Hub
                                spec:
                                    connectorRef: Docker_Quickstart
                                    repo: pavansa/citest
                                    tags:
                                        - <+pipeline.sequenceId>
